"""
@BY: Yang LIU
@DATE: 15-11-2020
"""


# Input: A string Text.
# Output: SuffixArray(Text).
def burrows_wheeler_transform_construction(text):
    
    length = len(text)
    array = []
    extended_text = text + text
    for i in range(length):
        array.append(extended_text[i:i+length])
    array.sort()
    symbol = ""
    for i in range(length):
        symbol += array[i][-1]
    return symbol


if __name__ == "__main__":   

    text = "CTACTCAATTTCAAATTCAAACACATAGACAACTAATCATCAATGGCATTAAGACTCTTAATAAGAAAATTTCCCTGTCGCTACTTCCGTATTCGTAAGCACATCACTATTCTCTAGTAATTCTTAAAGGAAAATATAGACGGCAGAGCTAAGGTGGTGTGACGCCGGTCAGGAGATGATCTCTTTCACCCTACAAAGCTAGGAGAGCGCAGATTCGTCTAAGGACGCGGTAGACATAGGGAAAAGGAATAGGGTCGGACTCTGACCGACGGGGGTTGGCCCTAGGTAGTTAAGAGACGTGGATTCGCTCTCACACTAAATCCATAACACAAGGAAGGGCGTCATGTGCGTGCGAGAAGCCGAGACCTTGTGTATCTTAGGGACTAACCTGGCCCTGTAAAACCTACGATCGATCAAAGGATGTTATGGCAGGACAAATAATGTCTAATTGTAACCGGGAAAGCTCCACTGATCCTTTTTTCTAGTATCTTCCAATCTAGAGCGGCGAAACTCGGAGGTTGTGTCAGAATATTATCAACTTAGCTACATTGAGGTCCAACCAGACTTGGCCTTACCTTATGAATGCACAAAAAAACTGGGGATCCGTGACTCTCTCTGTCGTACCAATATTTGGGCATTCCACGGGACGAGAGTCTCGTTGTCTGTTCTGGTCTTAACAGTCATTCGAATGTTAAGGGTATACGGCCTACAGTTTCTTGTGCAAAAACCTGTACTGTCACTTCTTATAAGTTCTCGGACGAGTCACAGTGTACCATGCCCCGAATGATTTTCCCTTCCAGGAGGGAAACATGAGTCATTAGTAGGTTGGCGTTGTTAGTCTC$"
    print(burrows_wheeler_transform_construction(text))